### ISSUE TITLE
:q

### ISSUE THREAD

**Issue by jabbalaci** [hakluke/how-to-exit-vim#125]
I may not be popular with this comment but could you mention the correct ways too?

```
:q     quit
:q!    force quit, don't save changes
:wq    write and quit
:x     shorthand for :wq
```
If a newbie gets here, (s)he may take these insane tips seriously...

**Comment by ScottKaye** [comment]
These commands don't really seem all that stable tbh, I'd rather use one of the commands listed in this repo tailored to my specific environment.

**Comment by jabbalaci** [comment]
@ScottKaye How are they unstable? Elaborate.

**Comment by aslafy-z** [comment]
Troll inside
