### ISSUE TITLE
The `xdotool` way

### ISSUE THREAD

**Issue by x3rAx** [hakluke/how-to-exit-vim#138]
I figured out another very convenient way to exit vim.

Why type complex commands yourself when `xdotool` can **do the work for you**?<sup>1</sup>

    :!(xdotool type ":e /tmp/exit.vim"; xdotool key KP_Enter; xdotool type "ggiquitall\!"; xdotool key KP_Enter; xdotool key Escape; xdotool type ":w"; xdotool key KP_Enter; xdotool type ":source /tmp/exit.vim"; xdotool key KP_Enter)&

**¯\\_(ツ)_/¯**

---
<sup>1</sup> Needs `xdotool` installed on your system

**Comment by hakluke** [comment]
hahaha! submit a pr!
