### ISSUE TITLE
Other ways

### ISSUE THREAD

**Issue by Rainmaker52** [hakluke/how-to-exit-vim#14]
How about the vi way?
:wq
:q!

Use :w!q not :wq!

Also, all of the other commands leave dotfiles behind.

Less seriously:
Ctrl-alt-f2, login again, use any of the ps commands.
Start with screen, detach or kill the active screen.
:!Killall vim
Use emacs or ed, like real men do

Simple, effective

**Comment by hakluke** [comment]
Couldn't get :q! to work. Not sure what you're talking about.

**Comment by Rainmaker52** [comment]
https://vim-adventures.com/

**Comment by hakluke** [comment]
What's vim?

**Comment by rahilwazir** [comment]
@Rainmaker52 That would not work. Check the readme for more easier methods.
