### ISSUE TITLE
：wq

### ISSUE THREAD

**Issue by willshion** [hakluke/how-to-exit-vim#150]

**Comment by RicardoHS** [comment]
does this really works?

**Comment by ThomasRedstone** [comment]
Nope, just ran vim and tried it, it says "E32: no file name".
Seems this is a dead end.

**Comment by Sodium-Aluminate** [comment]
not working in readonly files.

**Comment by ThomasRedstone** [comment]
Yeah, it really is a poor solution, luckily we have so many better alternatives.

**Comment by Sodium-Aluminate** [comment]
> Yeah, it really is a poor solution, luckily we have so many better alternatives.

~~like :!reboot~~

**Comment by hakluke** [comment]
This didn't work for me. Closing.

![image](https://user-images.githubusercontent.com/13975395/86071832-933f2700-bac3-11ea-8b1d-b6e0c2c9b650.png)
