### ISSUE TITLE
Formatting for "The canonical way"

### ISSUE THREAD

**Issue by ML-Chen** [hakluke/how-to-exit-vim#163]
Currently, "The canonical way" is part of the code block under the SEO Manager way section:

```sh
:call libcallnr('libc.so.6', 'exit', 0)

## The canonical way
Credit: @ligurio

```vim
:!q
```

when it seems that it's meant to be its own section.

I'd suggest adding a ``` after `:call libcallnr('libc.so.6', 'exit', 0)`.

**Comment by sehe** [comment]
Also, is it a joke that it says `:!q` instead of `:q!` or similar?

**Comment by ML-Chen** [comment]
Looks like this has been fixed.
