### ISSUE TITLE
Missing test cases

### ISSUE THREAD

**Issue by aberezin-acertus** [hakluke/how-to-exit-vim#166]
All this code is missing test cases.  One solution is to dockerize a test env however we will need a separate solution for the AWS (and later other cloud) ways.

**Comment by umarana** [comment]
maybe also add a guide for every OS :joy:

**Comment by Thesola10** [comment]
Also missing flexibility, what if I want to exit `nvim` instead of exiting `vim`??

**Comment by hakluke** [comment]
Full code overhaul needed. ETA March 2094
