### ISSUE TITLE
The PowerShell Core Way

### ISSUE THREAD

**Issue by Chirishman** [hakluke/how-to-exit-vim#174]
Given that VIM is much more likely to be found on a *nix box the PowerShell way needs amending to work cross-platform!

Here's how to do it with PowerShell Core (The executable name is different)

Also handles figuring out if you'll be needing it to stop vim or gvim ^__^

```PowerShell
pwsh -nol -nop -c {get-process  "$("g" * $IsWindows)vim" | stop-process}
```

**Comment by hakluke** [comment]
submit a pr
