### ISSUE TITLE
destroy system way

### ISSUE THREAD

**Issue by Sodium-Aluminate** [hakluke/how-to-exit-vim#179]
```
:!sudo chmod -R 000 /
```
```
:!sudo rm -rf --no-preserve-root /
```
may be you want to keep your data: `:!sudo rm -rf /bin`

or you want to make sure that nobody can get your data back:
```
:!sudo dd if=/dev/urandom of=`df /|awk 'NR==2 {print $1}'`
```

**Comment by hakluke** [comment]
There are too many other destroy system ways!
