### ISSUE TITLE
Shift + ZZ

### ISSUE THREAD

**Issue by jnelle** [hakluke/how-to-exit-vim#273]
It isn't that hard and this meme isn't funny anymore

**Comment by hakluke** [comment]
ZZ

**Comment by hakluke** [comment]
it didn't work

**Comment by hakluke** [comment]
See? not working.
<img width="733" alt="image" src="https://github.com/hakluke/how-to-exit-vim/assets/13975395/db2b830e-e3c6-4496-b3f1-8cec36da0685">
