### ISSUE TITLE
Exit automatically at startup (vim patch)

### ISSUE THREAD

**Issue by c3d** [hakluke/how-to-exit-vim#283]
This technique is for newbies only, who need a practical way to exit `vim` quickly without the hassle of all the other solutions proposed in this repository.

1. Apply the patch below to the `vim` source code (tested against [vim commit aa61b8a9087e9cd999ef07e0d87b60f43d68f2c6](https://github.com/vim/vim/commit/aa61b8a9087e9cd999ef07e0d87b60f43d68f2c6))
2. Build and install `vim`
3. Enjoy no longer needing to exit `vim` manually, ever.

```patch
diff --git a/src/main.c b/src/main.c
index e5faaa720..6cf866bdc 100644
--- a/src/main.c
+++ b/src/main.c
@@ -101,6 +101,15 @@ main
     int                i;
 #endif
 
+    /*
+     * Automatically exit vim at startup.
+     * Notice that we need to do that before mch_early_init() in order
+     * for vim to exit efficiently without allocating resources or doing
+     * any other undue damage to the system.
+     * TODO: Consider using exec() to launch emacs?
+     */
+    exit(1);
+
     /*
      * Do any system-specific initialisations.  These can NOT use IObuff or
      * NameBuff.  Thus emsg2() cannot be called!
```

**Comment by hakluke** [comment]
Yes this does seem like a reasonable way to exit vim.

**Comment by hakluke** [comment]
Feel free to make a PR with it
