### ISSUE TITLE
pkill vim

### ISSUE THREAD

**Issue by weissi** [hakluke/how-to-exit-vim#72]
I’m a `pkill` fan :)

    pkill vim

**Comment by abacao** [comment]
The correct way is:
`:!pkill -9 vim`

**Comment by keturn** [comment]
Hmm. That _seems_ to work for me, but it feels a little too reserved. Maybe we should kill vim and everything else on its terminal, just to be thorough. Something like this?

```
:!pkill --signal KILL --terminal $( ps --no-header -o tty $PPID )
```

**Comment by hakluke** [comment]
I like it.
